SELECT DISTINCT CODFIL, SUBSTR(IDENTPROC, 68, 9), SUBSTR(IDENTPROC, 33, 33)
FROM   MOV_PEDIDO A
WHERE  1 = 1
       AND A.DTPEDIDO = TO_DATE(SYSDATE - 1)     
       AND IDENTPROC NOT LIKE '%INTEGRACAO%'
UNION
SELECT DISTINCT SUBSTR(IDENTPROC, 68, 9), CODFIL, IDENTPROC
FROM   CRC_TITULO B
WHERE  B.DTEMISSAO >= SYSDATE - 3
       AND SUBSTR(IDENTPROC, 68, 1) = 'W'

UNION 

SELECT DISTINCT SUBSTR(IDENTPROC, 68, 9), CODFIL, IDENTPROC FROM CRC_LANCTO C
WHERE  C.DTMOVIM >= SYSDATE - 1
       AND SUBSTR(IDENTPROC, 68, 1) = 'W'

