SELECT A.CODFILIAL, A.CODPROMOC, A.DSCPROMOC, A.DSCCAMPAN, B.CODPRODUT, A.DATINICIO, A.DATFIM, P.DESCRICAO, B.PRECOVENDA, C.QTDREGRACADA, C.VLRDESCTO
FROM   DBASAT2_P.MP_PROMOC A
INNER  JOIN DBASAT2_P.MP_CESTA B ON A.CODPROMOC = B.CODPROMOC
INNER  JOIN DBASAT2_P.MP_REGRA C ON A.CODPROMOC = C.CODPROMOC
INNER  JOIN CAD_PROD P ON B.CODPRODUT = (P.CODPROD * 10) + P.DIGPROD
WHERE  1 = 1
--       AND A.CODFILIAL IN (5, 505)
       AND DATINICIO >= TO_DATE('01/10/2015', 'dd/mm/yyyy')

SELECT TO_DATE(DATFIM), TO_DATE(SYSDATE-1), A.* FROM DBASAT2_P.MP_PROMOC A
WHERE CODFILIAL IN (5, 505)
AND TO_DATE(DATFIM) >= TO_DATE(SYSDATE-1)
AND CODFILIAL = 5




SELECT A.CODFILIAL, A.CODPROMOC, A.DSCPROMOC, A.DSCCAMPAN, B.CODPRODUT, A.DATINICIO, A.DATFIM, P.DESCRICAO, B.PRECOVENDA, C.QTDREGRACADA, C.VLRDESCTO
FROM   DBASAT2_P.MP_PROMOC A
INNER  JOIN DBASAT2_P.MP_CESTA B ON A.CODPROMOC = B.CODPROMOC
INNER  JOIN DBASAT2_P.MP_REGRA C ON A.CODPROMOC = C.CODPROMOC
INNER  JOIN CAD_PROD P ON B.CODPRODUT = (P.CODPROD * 10) + P.DIGPROD
WHERE  1 = 1
--       AND A.CODFILIAL IN (5, 505)
         AND TO_DATE(DATFIM) >= TO_DATE(SYSDATE -1)
       AND DATINICIO >= TO_DATE('01/10/2015', 'dd/mm/yyyy')
