SELECT CODFIL, TPNOTA, NUMNOTA, SERIE, DTNOTA, DTATUEST, CONDPGTO, VLTOTAL, CODOPER, NUMPEDVEN, NRMULTRECEB, STATUS, IDENTPROC, MS.*
FROM   MOV_SAIDA MS
WHERE  1 = 1
AND MS.CODFIL = 1
AND MS.NUMCXA = 98
AND MS.DTNOTA = '18/03/2016'
--AND MS.NUMNOTA = 
--AND MS.VLTOTAL = 

ORDER BY VLTOTAL



SELECT *
FROM   MOV_SAIDA
WHERE  CODFIL = 2
       AND NUMCXA = 1
	  AND NUMNOTA = '13/01/2016'
	  
	  
	  
SELECT * FROM MOV_SAIDA A WHERE A.NUMNOT
