/* Análise de caixas abertos que contenham vendas */
SELECT T1.CODFIL Filial, T1.NUMCXA Caixa, T1.CODOPER "CODIGO OPERADOR", T1.DATAINI, T1.SITUACAO, ENDERECOIP, NOME "NOME OPERADOR", CODFUNC "CODIGO FUNCIONARIO", STATUS FROM (
SELECT CXM.CODFIL, CXM.NUMCXA, CXM.CODOPER, CXM.DATAINI, CXM.SITUACAO
FROM   CXA_MOVIMENTO CXM
WHERE  DATAINI = TO_DATE(SYSDATE, 'DD/MM/YY')
       AND NUMMOV = 1
       AND EXISTS (SELECT 1
        FROM   MOV_SAIDA MS
        WHERE  MS.CODFIL = CXM.CODFIL
	     AND MS.NUMCXA = CXM.NUMCXA
	     AND MS.DTNOTA = CXM.DATAINI
               AND MS.VLTOTAL > 0)) T1

LEFT JOIN PDV_FISCAL PF
ON T1.CODFIL = PF.CODFIL
AND T1.NUMCXA = PF.PDV
AND T1.DATAINI = PF.DATA
AND PF.TIPO = 'A'

LEFT JOIN CXA_OPERADOR CO
ON T1.CODFIL = CO.CODFIL
AND T1.CODOPER = CO.CODOPER
