SELECT A.FILIAL, A.NUMCUPOM, A.NUMCXA, A.VLTRANSACAO, SUM(B.VALLAN), (A.VLTRANSACAO - SUM(B.VALLAN)) DIV, B.CODOPER, A.HRTRANSACAO,
A.STATUS, A.STATUS_TEF, A.NUMDOCUMENTO, A.AUTORIZACAO, B.CODEVE, B.CODCON, B.DATENT

FROM   TRANSACOES_TEF A, CXA_LANCTO     B

WHERE  A.FILIAL = B.CODFIL
      --and b.numnot = a.numcupom
       and b.datent = trunc (a.dttransacao)
       AND A.NUMCXA = B.NUMCXA
       AND A.FILIAL = 12
       AND A.numcxa = 74
       AND B.DATENT = TO_DATE('&DATA')
       AND A.STATUS <> 9
       AND B.STATUS = 2
       AND A.NUMDOCUMENTO = B.NUMDOC

GROUP  BY A.FILIAL,
	A.NUMCUPOM,
	A.NUMCXA,
	B.CODOPER,
	A.VLTRANSACAO,
	A.HRTRANSACAO,
	A.STATUS,
	A.STATUS_TEF,
	A.NUMDOCUMENTO,
	A.AUTORIZACAO,
	B.CODEVE,
	B.CODCON,
	B.DATENT  
