	SELECT CALL_REQ.REF_NUM AS 'CHAMADO'
		  ,CALL_REQ.DESCRIPTION AS 'DESCRICAO'
		  ,CNT.LAST_NAME AS 'SOLICITANTE'
		  ,LOC.LOCATION_NAME AS 'LOCALIDADE'
		  ,DEPT.NAME AS 'DEPTO_SOLICITANTE'
		  ,ASS.LAST_NAME AS 'RESPONSAVEL'
		  ,GRP.LAST_NAME AS 'GRUPO'
		  ,STAT.SYM AS 'STATUS'
		  ,CONVERT(VARCHAR, DATEADD(HOUR, -3, DATEADD(S, CALL_REQ.open_date, '1970-01-01')), 103) + ' ' + CONVERT(VARCHAR, DATEADD(HOUR, -3, DATEADD(S, CALL_REQ.open_date, '1970-01-01')), 108) AS 'DATA_ABERTURA'
		  ,CONVERT(VARCHAR, DATEADD(HOUR, -3, DATEADD(S, CALL_REQ.close_date, '1970-01-01')), 103) + ' ' + CONVERT(VARCHAR, DATEADD(HOUR, -3, DATEADD(S, CALL_REQ.close_date, '1970-01-01')), 108) AS 'DATA_ENCERRAMENTO'
		  ,CONVERT(VARCHAR, DATEADD(HOUR, -3, DATEADD(S, CALL_REQ.resolve_date, '1970-01-01')), 103) + ' ' + CONVERT(VARCHAR, DATEADD(HOUR, -3, DATEADD(S, CALL_REQ.resolve_date, '1970-01-01')), 108) AS 'DATA_RESOLUCAO'
		  ,CALL_REQ.CUSTOMER AS 'COD_SOLICITANTE'
		  ,CALL_REQ.CATEGORY AS 'COD_CATEGORIA'
		  ,CTG.SYM AS 'CATEGORIA'
		  ,CALL_REQ.priority AS 'PRIORIDADE'
		  ,CALL_REQ.MACRO_PREDICT_VIOL AS 'CHAM_POSS_VIOLACAO'
		  ,CALL_REQ.SLA_VIOLATION AS 'SLA_VIOLADO'
		  ,CALL_REQ.TYPE AS 'TP_CHAMADO'
		 ,CONVERT(VARCHAR(25), GETDATE(), 120) AS 'DT_H_EXTRACAO'
	--call_req.status as'COD_STATUS', 

	FROM   CALL_REQ WITH(NOLOCK)

	INNER  JOIN CR_STAT AS STAT
	ON     STAT.CODE = CALL_REQ.STATUS
	LEFT   JOIN CA_CONTACT AS CNT
	ON     CNT.CONTACT_UUID = CALL_REQ.REQUESTED_BY
	LEFT   JOIN CA_CONTACT AS GRP
	ON     GRP.CONTACT_UUID = CALL_REQ.GROUP_ID
	LEFT   JOIN CA_CONTACT AS ASS
	ON     ASS.CONTACT_UUID = CALL_REQ.ASSIGNEE
	LEFT   JOIN CA_LOCATION AS LOC
	ON     LOC.LOCATION_UUID = CNT.LOCATION_UUID
	LEFT   JOIN CA_RESOURCE_DEPARTMENT AS DEPT
	ON     DEPT.ID = CNT.DEPARTMENT
	LEFT   JOIN PROB_CTG AS CTG
	ON     CTG.PERSID = CALL_REQ.CATEGORY

	WHERE ASS.last_name LIKE '%YURI%'
	AND status != 'Encerrado'

	
	UNION ALL

	SELECT REF_NUM AS 'CHAMADO'
		  ,ISSUE.DESCRIPTION AS 'DESCRICAO'
		  ,CNT.LAST_NAME AS 'SOLICITANTE'
		  ,LOC.LOCATION_NAME AS 'LOCALIDADE'
		  ,DEPT.NAME AS 'DEPTO_SOLICITANTE'
		  ,ASS.LAST_NAME AS 'RESPONSAVEL'
		  ,GRP.LAST_NAME AS 'GRUPO'
		  ,STAT.SYM AS 'STATUS'
		  ,CONVERT(VARCHAR, DATEADD(HOUR, -3, DATEADD(S, ISSUE.open_date, '1970-01-01')), 103) + ' ' + CONVERT(VARCHAR, DATEADD(HOUR, -3, DATEADD(S, ISSUE.open_date, '1970-01-01')), 108) AS 'DATA_ABERTURA'
		  ,CONVERT(VARCHAR, DATEADD(HOUR, -3, DATEADD(S, ISSUE.close_date, '1970-01-01')), 103) + ' ' + CONVERT(VARCHAR, DATEADD(HOUR, -3, DATEADD(S, ISSUE.close_date, '1970-01-01')), 108) AS 'DATA_ENCERRAMENTO'
		  ,CONVERT(VARCHAR, DATEADD(HOUR, -3, DATEADD(S, ISSUE.resolve_date, '1970-01-01')), 103) + ' ' + CONVERT(VARCHAR, DATEADD(HOUR, -3, DATEADD(S, ISSUE.resolve_date, '1970-01-01')), 108) AS 'DATA_RESOLUCAO'
		  ,REQUESTOR AS 'COD_SOLICITANTE'
		  ,CAT.PERSID AS 'COD_CATEGORIA'
		  ,CAT.SYM AS 'CATEGORIA'
		  ,ISSUE.priority AS 'PRIORIDADE'
		  ,ISSUE.MACRO_PREDICT_VIOL AS 'CHAM_POSS_VIOLACAO'
		  ,ISSUE.SLA_VIOLATION AS 'SLA_VIOLADO'
		  ,'RDS' AS TP_CHAMADO
		  ,CONVERT(VARCHAR(25), GETDATE(), 120) AS 'DT_H_EXTRACAO'

	FROM   ISSUE WITH(NOLOCK)

	LEFT   JOIN CA_CONTACT AS CNT
	ON     CNT.CONTACT_UUID = ISSUE.REQUESTED_BY
	LEFT   JOIN CA_CONTACT AS GRP
	ON     GRP.CONTACT_UUID = ISSUE.GROUP_ID
	LEFT   JOIN CA_CONTACT AS ASS
	ON     ASS.CONTACT_UUID = ISSUE.ASSIGNEE
	LEFT   JOIN CA_LOCATION AS LOC
	ON     LOC.LOCATION_UUID = CNT.LOCATION_UUID
	LEFT   JOIN CA_RESOURCE_DEPARTMENT AS DEPT
	ON     DEPT.ID = CNT.DEPARTMENT
	LEFT   JOIN ISSSTAT AS STAT
	ON     STAT.CODE = ISSUE.STATUS
	LEFT   JOIN ISSCAT AS CAT
	ON     CAT.CODE = ISSUE.CATEGORY
	
	WHERE ASS.last_name LIKE '%YURI%'
	AND status != 'Encerrado'


SELECT 
c.userid,
c.last_name, 
c.department,
c.job_title, 
c.pri_phone_number,
c.fax_number,
c.supervisor_contact_uuid,
cd.name,
dep.name

FROM CA_CONTACT AS c

left join ca_contact_type AS cd
on C.contact_type = cd.id

left join ca_resource_department as dep
on C.department = dep.id
WHERE last_name like 'Yuri%' or userid = '51018466'


--Rastreamento de tabelas que conhtenham conteúdo

select top(50) * from ca_application_registration --Registro de aplicação
select top(50) * from ca_asset -- label dos sistemas da leroy merlin
select top(50) * from ca_contact
select top(50) * from ca_contact_type
select top(50) * from ca_resource_department 
select top(50) * from
select top(50) * from
select top(50) * from
