	SELECT CALL_REQ.REF_NUM AS 'CHAMADO'
		  ,CALL_REQ.DESCRIPTION AS 'DESCRICAO'
		  ,CNT.LAST_NAME AS 'SOLICITANTE'
		  ,LOC.LOCATION_NAME AS 'LOCALIDADE'
		  ,DEPT.NAME AS 'DEPTO_SOLICITANTE'
		  ,ASS.LAST_NAME AS 'RESPONSAVEL'
		  ,GRP.LAST_NAME AS 'GRUPO'
		  ,STAT.SYM AS 'STATUS'
		  ,CONVERT(VARCHAR, DATEADD(HOUR, -3, DATEADD(S, CALL_REQ.open_date, '1970-01-01')), 103) + ' ' + CONVERT(VARCHAR, DATEADD(HOUR, -3, DATEADD(S, CALL_REQ.open_date, '1970-01-01')), 108) AS 'DATA_ABERTURA'
		  ,CONVERT(VARCHAR, DATEADD(HOUR, -3, DATEADD(S, CALL_REQ.close_date, '1970-01-01')), 103) + ' ' + CONVERT(VARCHAR, DATEADD(HOUR, -3, DATEADD(S, CALL_REQ.close_date, '1970-01-01')), 108) AS 'DATA_ENCERRAMENTO'
		  ,CONVERT(VARCHAR, DATEADD(HOUR, -3, DATEADD(S, CALL_REQ.resolve_date, '1970-01-01')), 103) + ' ' + CONVERT(VARCHAR, DATEADD(HOUR, -3, DATEADD(S, CALL_REQ.resolve_date, '1970-01-01')), 108) AS 'DATA_RESOLUCAO'
		  ,CALL_REQ.CUSTOMER AS 'COD_SOLICITANTE'
		  ,CALL_REQ.CATEGORY AS 'COD_CATEGORIA'
		  ,CTG.SYM AS 'CATEGORIA'
		  ,CALL_REQ.priority AS 'PRIORIDADE'
		  ,CALL_REQ.MACRO_PREDICT_VIOL AS 'CHAM_POSS_VIOLACAO'
		  ,CALL_REQ.SLA_VIOLATION AS 'SLA_VIOLADO'
		  ,CALL_REQ.TYPE AS 'TP_CHAMADO'
		 ,CONVERT(VARCHAR(25), GETDATE(), 120) AS 'DT_H_EXTRACAO'

	--call_req.status as'COD_STATUS', 

	FROM   CALL_REQ WITH(NOLOCK)

	INNER  JOIN CR_STAT AS STAT
	ON     STAT.CODE = CALL_REQ.STATUS
	LEFT   JOIN CA_CONTACT AS CNT
	ON     CNT.CONTACT_UUID = CALL_REQ.REQUESTED_BY
	LEFT   JOIN CA_CONTACT AS GRP
	ON     GRP.CONTACT_UUID = CALL_REQ.GROUP_ID
	LEFT   JOIN CA_CONTACT AS ASS
	ON     ASS.CONTACT_UUID = CALL_REQ.ASSIGNEE
	LEFT   JOIN CA_LOCATION AS LOC
	ON     LOC.LOCATION_UUID = CNT.LOCATION_UUID
	LEFT   JOIN CA_RESOURCE_DEPARTMENT AS DEPT
	ON     DEPT.ID = CNT.DEPARTMENT
	LEFT   JOIN PROB_CTG AS CTG
	ON     CTG.PERSID = CALL_REQ.CATEGORY

	WHERE 1=1
	and ASS.last_name LIKE '%Yuri%'
	--and REF_NUM = '56359'

	
	UNION ALL

	SELECT REF_NUM AS 'CHAMADO'
		  ,ISSUE.DESCRIPTION AS 'DESCRICAO'
		  ,CNT.LAST_NAME AS 'SOLICITANTE'
		  ,LOC.LOCATION_NAME AS 'LOCALIDADE'
		  ,DEPT.NAME AS 'DEPTO_SOLICITANTE'
		  ,ASS.LAST_NAME AS 'RESPONSAVEL'
		  ,GRP.LAST_NAME AS 'GRUPO'
		  ,STAT.SYM AS 'STATUS'
		  ,CONVERT(VARCHAR, DATEADD(HOUR, -3, DATEADD(S, ISSUE.open_date, '1970-01-01')), 103) + ' ' + CONVERT(VARCHAR, DATEADD(HOUR, -3, DATEADD(S, ISSUE.open_date, '1970-01-01')), 108) AS 'DATA_ABERTURA'
		  ,CONVERT(VARCHAR, DATEADD(HOUR, -3, DATEADD(S, ISSUE.close_date, '1970-01-01')), 103) + ' ' + CONVERT(VARCHAR, DATEADD(HOUR, -3, DATEADD(S, ISSUE.close_date, '1970-01-01')), 108) AS 'DATA_ENCERRAMENTO'
		  ,CONVERT(VARCHAR, DATEADD(HOUR, -3, DATEADD(S, ISSUE.resolve_date, '1970-01-01')), 103) + ' ' + CONVERT(VARCHAR, DATEADD(HOUR, -3, DATEADD(S, ISSUE.resolve_date, '1970-01-01')), 108) AS 'DATA_RESOLUCAO'
		  ,REQUESTOR AS 'COD_SOLICITANTE'
		  ,CAT.PERSID AS 'COD_CATEGORIA'
		  ,CAT.SYM AS 'CATEGORIA'
		  ,ISSUE.priority AS 'PRIORIDADE'
		  ,ISSUE.MACRO_PREDICT_VIOL AS 'CHAM_POSS_VIOLACAO'
		  ,ISSUE.SLA_VIOLATION AS 'SLA_VIOLADO'
		  ,'RDS' AS TP_CHAMADO
		  ,CONVERT(VARCHAR(25), GETDATE(), 120) AS 'DT_H_EXTRACAO'

	FROM   ISSUE WITH(NOLOCK)

	LEFT   JOIN CA_CONTACT AS CNT
	ON     CNT.CONTACT_UUID = ISSUE.REQUESTED_BY
	LEFT   JOIN CA_CONTACT AS GRP
	ON     GRP.CONTACT_UUID = ISSUE.GROUP_ID
	LEFT   JOIN CA_CONTACT AS ASS
	ON     ASS.CONTACT_UUID = ISSUE.ASSIGNEE
	LEFT   JOIN CA_LOCATION AS LOC
	ON     LOC.LOCATION_UUID = CNT.LOCATION_UUID
	LEFT   JOIN CA_RESOURCE_DEPARTMENT AS DEPT
	ON     DEPT.ID = CNT.DEPARTMENT
	LEFT   JOIN ISSSTAT AS STAT
	ON     STAT.CODE = ISSUE.STATUS
	LEFT   JOIN ISSCAT AS CAT
	ON     CAT.CODE = ISSUE.CATEGORY
	
	WHERE 1=1
	and ASS.last_name LIKE '%Yuri%'
	--and GRP.LAST_NAME = 'N2 LEGADOS'
	--and REF_NUM = '56359'